package(default_visibility = ["//visibility:public"])

cc_test(
    name = "curve_fitting_test",
    srcs = ["curve_fitting_test.cc"],
    deps = [
        "//vins/backend:problem",
        "@com_google_googletest//:gtest_main",
    ],
)
