package(default_visibility = ["//visibility:public"])

cc_library(
    name = "vertex",
    srcs = [
        "vertex_pose.cc",
        "vertex.cc",
    ],
    hdrs = [
        "vertex_inverse_depth.h",
        "vertex_point_xyz.h",
        "vertex_pose.h",
        "vertex_scale.h",
        "vertex_speedbias.h",
        "vertex.h",
    ],
    deps = [
        "//vins/backend/common:eigen_types",
    ],
)
