package(default_visibility = ["//visibility:public"])

proto_library(
    name = "vins_config_proto",
    srcs = ["vins_config.proto"],
    deps = [
    ],
)

cc_proto_library(
    name = "vins_config_cc_proto",
    deps = [
        ":vins_config_proto",
    ],
)
